services: 
  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment: 
      - MONGO_INITDB_DATABASE=local
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports: 
      - '27017-27019:27017-27019'